packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@tailwindcss/postcss": "^4.1.11"
  "@types/node": "^20.19.9"
  "@types/react": "^19.1.9"
  "@types/react-dom": "^19.1.7"
  "eslint": "^9.32.0"
  "typescript": "^5.9.2"
  "postcss": "^8.4.35"
  "zod": "^3"
  "@turbo/gen": "^2.6.1"
  "tailwindcss": "^4.1.11"
  "vitest": "^4.0.18"
  "@vitest/coverage-v8": "^4.0.18"
  "dotenv": "^16.4.7"
  "pg": ^8.18.0
  "@types/pg": ^8.16.0
