/**
 * Shared constants for the route-action-gen CLI.
 */

export const GENERATED_NOTICE =
  "THIS FILE IS AUTOMATICALLY GENERATED BY ROUTE-ACTION-GEN";

export const GENERATED_HEADER = `/** ${GENERATED_NOTICE} **/
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck`;
