/** THIS FILE IS AUTOMATICALLY GENERATED BY ROUTE-ACTION-GEN **/
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
import type {
  requestValidator as getRequestValidator,
  responseValidator as getResponseValidator,
} from "../../../../../pages/api/posts/[postId]/route.get.config";
import type {
  requestValidator as postRequestValidator,
  responseValidator as postResponseValidator,
} from "../../../../../pages/api/posts/[postId]/route.post.config";
import { z } from "zod";

/**
 * The client class that can be used to call the route handler from a non-React app.
 *
 * @returns The client class.
 */
export class RouteClient {
  /**
   * The get method that can be used to call the route handler from a non-React app.
   */
  async get(inputData: {
    params: z.infer<NonNullable<(typeof getRequestValidator)["params"]>>;
  }): Promise<z.infer<typeof getResponseValidator>> {
    const response = await fetch(`/api/posts/${inputData.params.postId}`, {
      method: "get",
    });

    if (!response.ok) {
      const errorBody = await response.json();
      throw new Error(errorBody.message ?? response.statusText);
    }

    const responseData = await response.json();
    return responseData as z.infer<typeof getResponseValidator>;
  }

  /**
   * The post method that can be used to call the route handler from a non-React app.
   */
  async post(inputData: {
    body: z.infer<NonNullable<(typeof postRequestValidator)["body"]>>;
    params: z.infer<NonNullable<(typeof postRequestValidator)["params"]>>;
  }): Promise<z.infer<typeof postResponseValidator>> {
    const response = await fetch(`/api/posts/${inputData.params.postId}`, {
      method: "post",
      credentials: "include",
      body: JSON.stringify(inputData.body),
      headers: {
        "Content-Type": "application/json",
      },
    });

    if (!response.ok) {
      const errorBody = await response.json();
      throw new Error(errorBody.message ?? response.statusText);
    }

    const responseData = await response.json();
    return responseData as z.infer<typeof postResponseValidator>;
  }
}
