/** THIS FILE IS AUTOMATICALLY GENERATED BY ROUTE-ACTION-GEN **/
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck

import { createPagesRoute } from "route-action-gen/lib/next/pages";
import {
  handler as getHandler,
  requestValidator as getRequestValidator,
  responseValidator as getResponseValidator,
} from "../../../../../pages/api/posts/[postId]/route.get.config";
import {
  handler as postHandler,
  requestValidator as postRequestValidator,
  responseValidator as postResponseValidator,
} from "../../../../../pages/api/posts/[postId]/route.post.config";

/**
 * Next.js Pages Router API route handler.
 *
 * Dispatches to the correct method handler based on `req.method`.
 * Validates request body, params, headers, and search params before
 * calling the handler. Returns 405 for unsupported methods.
 */
export default createPagesRoute(
  {
    get: {
      requestValidator: getRequestValidator,
      responseValidator: getResponseValidator,
      handler: getHandler,
    },
    post: {
      requestValidator: postRequestValidator,
      responseValidator: postResponseValidator,
      handler: postHandler,
    },
  },
  ["postId"],
);
