/** THIS FILE IS AUTOMATICALLY GENERATED BY ROUTE-ACTION-GEN **/
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
import type {
  requestValidator as deleteRequestValidator,
  responseValidator as deleteResponseValidator,
} from "../../../../../pages/api/posts/[postId]/route.delete.config";
import { z } from "zod";

/**
 * The client class that can be used to call the route handler from a non-React app.
 *
 * @returns The client class.
 */
export class RouteClient {
  /**
   * The delete method that can be used to call the route handler from a non-React app.
   */
  async delete(inputData: {
    params: z.infer<NonNullable<(typeof deleteRequestValidator)["params"]>>;
  }): Promise<z.infer<typeof deleteResponseValidator>> {
    const response = await fetch(`/api/posts/${inputData.params.postId}`, {
      method: "delete",
    });

    if (!response.ok) {
      const errorBody = await response.json();
      throw new Error(errorBody.message ?? response.statusText);
    }

    const responseData = await response.json();
    return responseData as z.infer<typeof deleteResponseValidator>;
  }
}
