/** THIS FILE IS AUTOMATICALLY GENERATED BY ROUTE-ACTION-GEN **/
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck

import { createPagesRoute } from "route-action-gen/lib/next/pages";
import {
  handler as deleteHandler,
  requestValidator as deleteRequestValidator,
  responseValidator as deleteResponseValidator,
} from "../../../../../pages/api/posts/[postId]/route.delete.config";

/**
 * Next.js Pages Router API route handler.
 *
 * Dispatches to the correct method handler based on `req.method`.
 * Validates request body, params, headers, and search params before
 * calling the handler. Returns 405 for unsupported methods.
 */
export default createPagesRoute(
  {
    delete: {
      requestValidator: deleteRequestValidator,
      responseValidator: deleteResponseValidator,
      handler: deleteHandler,
    },
  },
  ["postId"],
);
