// This file is automatically generated by [env-to-t3 CLI](https://github.com/nicnocquee/env-to-t3)

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    DB_POOLING_URL: z.string().min(1),
    DB_URL_NON_POOLING: z.string().min(1),
    DB_CERT_BASE_64: z.string().optional(),
  },
  client: {
    NEXT_PUBLIC_DEFAULT_LANGUAGE: z.string().min(1),
    NEXT_PUBLIC_DEFAULT_TIMEOUT_MS: z.number({ coerce: true }).optional(),
  },
  experimental__runtimeEnv: {
    NEXT_PUBLIC_DEFAULT_LANGUAGE: process.env.NEXT_PUBLIC_DEFAULT_LANGUAGE,
    NEXT_PUBLIC_DEFAULT_TIMEOUT_MS: process.env.NEXT_PUBLIC_DEFAULT_TIMEOUT_MS,
  }
});
