/** THIS FILE IS AUTOMATICALLY GENERATED BY ROUTE-ACTION-GEN **/
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
"use client";
import { createInput, createLabel } from "route-action-gen/lib/react";

/**
 * The form components. The key is the name of the input field. The value is an object with the `input` and `label` components.
 * - `input` is the input React component and
 * - `label` is the label React component.
 *
 */
export const formComponents = {
  "body.title": {
    input: createInput({
      name: "body.title",
      type: "text",
      id: "body.title",
    }),
    label: createLabel({ id: "body.title", placeholderChildren: "Title" }),
  },
  "body.content": {
    input: createInput({
      name: "body.content",
      type: "text",
      id: "body.content",
    }),
    label: createLabel({ id: "body.content", placeholderChildren: "Content" }),
  },
  "params.postId": {
    input: createInput({
      name: "params.postId",
      type: "text",
      id: "params.postId",
      minLength: 1,
    }),
    label: createLabel({ id: "params.postId", placeholderChildren: "Post Id" }),
  },
};
