/** THIS FILE IS AUTOMATICALLY GENERATED BY ROUTE-ACTION-GEN **/
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
"use server";

import {
  handler,
  requestValidator,
  responseValidator,
} from "../route.post.config";
import { createFormAction } from "route-action-gen/lib/next";

/**
 * The form action that executes the handler function in the `route.post.config.ts` file.
 *
 * @returns The form action.
 */
export const formAction = createFormAction(
  requestValidator,
  responseValidator,
  handler,
);
