/** THIS FILE IS AUTOMATICALLY GENERATED BY ROUTE-ACTION-GEN **/
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
"use server";

import {
  handler,
  requestValidator,
  responseValidator,
} from "../route.post.config";
import { createServerFunction } from "route-action-gen/lib/next";

/**
 * The server function that executes the handler function in the `route.post.config.ts` file.
 *
 * @returns The server function.
 */
export const serverFunction = createServerFunction(
  requestValidator,
  responseValidator,
  handler,
);
