/** THIS FILE IS AUTOMATICALLY GENERATED BY ROUTE-ACTION-GEN **/
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
"use client";

import { useCallback, useMemo, useState, useTransition } from "react";
import { responseValidator } from "../route.post.config";
import { serverFunction } from "./server.function";
import { z } from "zod";

/**
 * A custom hook to use the server function that executes the handler function in the `server.function.ts` file.
 *
 * @returns An object with the `pending`, `fetchData`, `error`, and `data` properties.
 */
export const useServerFunction = () => {
  const [pending, startTransition] = useTransition();

  const [error, setError] = useState<string | null>(null);
  const [data, setData] = useState<z.infer<typeof responseValidator> | null>(
    null,
  );
  const fetchData = useCallback(
    async (payload: Parameters<typeof serverFunction>[0]) => {
      startTransition(async () => {
        const result = await serverFunction(payload);
        if (result.status === false) {
          setError(result.message);
        } else {
          setData(result.data);
        }
      });
    },
    [startTransition],
  );

  return useMemo(
    () => ({
      pending,
      fetchData,
      error,
      data,
    }),
    [pending, error, data, fetchData],
  );
};
